### ISSUE TITLE
0x9101 code example

### ISSUE THREAD

**Issue by Licymnius** [SmallChi/JT1078#12]
Could you please provide a small example how can I send a 0x9101 code to start multimedia streaming.

**Comment by SmallChi** [comment]
Sorry for not replying in time,Please refer to the following link.
[workflow](https://www.hentai.org.cn/article?id=8)

**Comment by Licymnius** [comment]
I started JT1078.Gateway.TestNormalHosting with 7704 and 7705 ports . Then, after authorisation, I send via jt808 0x9101 command, but JT1078 doesn't receive any packets.

 ```
public override byte[] Msg0x0102(JT808HeaderPackage request, IJT808Session session)
        {
            JT808_0x9101 jT808_0X9101 = new JT808_0x9101();
            jT808_0X9101.ServerIPAddress = "192.168.1.56";
            jT808_0X9101.ServerVideoChannelTcpPort = 7704;
            jT808_0X9101.ServerVideoChannelUdpPort = 7705;
            jT808_0X9101.LogicalChannelNo = 1;
            jT808_0X9101.DataType = 1;
            jT808_0X9101.StreamType = 1;
            jT808_0X9101.ServerIPAddressLength = 12;

            JT808Package jT808Package = new JT808Package
            {
                Header = new JT808Header
                {
                    MsgId = 37121.ToUInt16Value(),
                    MsgNum = request.Header.MsgNum,
                    TerminalPhoneNo = session.TerminalPhoneNo,
                    MessageBodyProperty = new JT808HeaderMessageBodyProperty()
                },
                Bodies = jT808_0X9101

            };
            
            session.SendAsync(jT808Serializer.Serialize(jT808Package));

            return base.Msg0x0102(request, session);
        }
```

What can I do wrong?

**Comment by SmallChi** [comment]
1. Check whether the equipment supports 1078 protocol
2. Use the simple Tcp Server tool as the 1078Gateway
3. Try to issue the command 0x9101 to the device
4. If the device can connect to TCP Server and send data, there is no problem with the command.

**Comment by Licymnius** [comment]
Thanks a lot. The problem was in a protocol version. The device doesn't support 2019 one.
I set an old protocol in JT808HeaderMessageBodyProperty and enabled 1078 stream.
Thanks for this great library. It's a hard job to move bricks :) 
Do you have any plans to add sound support in the nearest future?

**Comment by SmallChi** [comment]
The audio is planned, but it will take a little longer.

**Comment by Licymnius** [comment]
Great! Thanks!
