### ISSUE TITLE
您好 请问 下发0x9102指令 切换码流（主码流,子码流 ）切换不成功 

### ISSUE THREAD

**Issue by MrShenf** [SmallChi/JT1078#15]
JT808_0x9102 jT808_0X9102 = new JT808_0x9102();
                jT808_0X9102.ChannelNo = channel;
                jT808_0X9102.ControlCmd = controlcmd;
                jT808_0X9102.StreamType = streamtype;
                JT808Package jT808Package = new JT808Package
                {
                    Header = new JT808Header
                    {
                        MsgId = JT808_JT1078_MsgId.音视频实时传输控制.ToUInt16Value(),
                        MsgNum = msgNum,
                        TerminalPhoneNo = sim,
                        MessageBodyProperty = new JT808HeaderMessageBodyProperty()
                    },
                    Bodies = jT808_0X9102
                };
                var byteData = JT808Serializer.Serialize(jT808Package);
                result = jT808UnificationSendService.Send(sim, byteData);

**Comment by SmallChi** [comment]
设备支不支持切换？

**Comment by MrShenf** [comment]
> 设备支不支持切换？

支持 下发0x9101指令 时候传StreamType=0 是主码流 清晰的  传StreamType=1 是次码流 不清晰的     
下发0x9102指令切换传ControlCmd=1  StreamType=0（或1）能下发消息成功 然后视频流开始花屏出现马赛克

**Comment by MrShenf** [comment]
![image](https://user-images.githubusercontent.com/10752947/147805835-11bdea3f-79bb-4e70-90f1-83f60d5e3285.png)
![image](https://user-images.githubusercontent.com/10752947/147805852-e6f54fff-e3df-4ae0-8a47-b49636aa52b5.png)

**Comment by SmallChi** [comment]
噢  这个有点忘记了，切换的时候有重新发flv头信息吗？要是能忍受断开的话，可以切换的时候断开然后进行重连一下。

**Comment by MrShenf** [comment]
> 噢 这个有点忘记了，切换的时候有重新发flv头信息吗？要是能忍受断开的话，可以切换的时候断开然后进行重连一下。

是指前端页面重新加载一下flv视频地址是吗  试了一下这样貌似切换可以成功 感谢

**Comment by SmallChi** [comment]
不客气，这个是最简单暴力的方式。 哈哈 😂
