### ISSUE TITLE
您好 考虑后续增加 推送到 ZLMediaKit（https://github.com/ZLMediaKit/ZLMediaKit） 流媒体作为服务器吗

### ISSUE THREAD

**Issue by MrShenf** [SmallChi/JT1078#16]

**Comment by SmallChi** [comment]
1.这个项目本身只是作为实验性的，主要是学习音视频的编解码，没有打算集成第三方的流媒体服务器；
2.需要集成第三方的如：ZLMediaKit或者SRS，那就再1078网关那边收到数据之后再往相应的地方进行转发，这个可以自己实现，并不是什么难事；
3.本身1078网关就可以提供推流，没有必要再转发到ZLMediaKit或者SRS上面，目前已经实现flv、hls的视频推流，FMp4+MSE和音频部分也在进行中。

**Comment by MrShenf** [comment]
> 
好的 谢谢
