### ISSUE TITLE
关于自定义位置附加工厂

### ISSUE THREAD

**Issue by locialchu** [SmallChi/JT1078#17]
厂商AttachInfoId一位AttachInfoLength两位，参考DEMO10的代码，但是
IJT808Config接口中的IJT808_0x0200_Custom_Factory也是自定义实现的，我在引用nuget包版本的情况下应该如何修改呢

**Comment by SmallChi** [comment]
可以参考任意808项目的扩展，例如：1078、苏标、粤标，另外还有[锐明的扩展](https://github.com/lishewen/Streamax.Protocol)

**Comment by SmallChi** [comment]
@locialchu 刚看了下，抱歉，目前不支持厂商1位和附加长度2位的，因为没有遇到过，方便提供一下对应协议和hex数据吗？

**Comment by locialchu** [comment]
> 

@SmallChi 抱歉啊，是我看错了，他是1:1的，但是对于2:1和2:2的实现还是不太清楚

**Comment by SmallChi** [comment]
好的，1:1的你参考808项目下面的扩展和demo那些就知道怎么搞了。
