### ISSUE TITLE
视频延迟问题

### ISSUE THREAD

**Issue by wangyl006** [SmallChi/JT1078#9]
我今天部署到阿里云服务器。在客户端访问有15秒左右的延迟。这个延迟有点高。大神哪里需要修改配置吗？谢谢

**Comment by SmallChi** [comment]
大兄弟，应该不至于的，客户端用什么播放的？

**Comment by wangyl006** [comment]
> 大兄弟，应该不至于的，客户端用什么播放的？

用的是里面自带的，我在windows服务器部署的。centos没部署成功。跟这个又关系吗？

**Comment by SmallChi** [comment]
应该没有多大关系吧⊙﹏⊙ 应该是你的姿势不对导致的😄

**Comment by wangyl006** [comment]
好吧。我基本是没修改什么就控制。针对链接的sim卡。我把日志打印去掉了

**Comment by SmallChi** [comment]
有微信吗？可以加个在里面聊方便点

**Comment by wangyl006** [comment]
wangyl006
